### ISSUE TITLE
sbteclipse-plugin;4.0.0: not found

### ISSUE THREAD

**Issue by henrykey** [typesafehub/sbteclipse#315]
Hi, I just tried the plugin as mentioned in README to put that line into plugins.sbt. It's failure to run eclipse and got following information:
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13) (/Users/kehongwei/.sbt/0.13/plugins.sbt#L1-2)
[warn] 		  +- net.ruippeixotog:scala-scraper_2.11:1.0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[error] Total time: 4 s, completed 2016-4-17 10:33:56

what should I'm going to do for fixing this?

Thanks,

Henry

**Comment by 2m** [comment]
Hey. Which sbt version are you using? It looks like it tries to resolve `sbteclipse` plugin for scala 2.11, but current sbt version `0.13.11` is compiled under `2.10` AFAIK.

Where is your `plugins.sbt` located?

**Comment by ryanstull** [comment]
I'm getting the same issue as well.  I'm using the latest version of SBT with scala 2.11.7 .   However I looked on maven central and it seems like the project no longer exists under com.typesafe, as far as I can tell.

**Comment by 2m** [comment]
This sbt plugin is published to bintray under [`sbt/sbt-plugin-releases`](https://bintray.com/sbt/sbt-plugin-releases/sbteclipse/view) which is where sbt looks for sbt plugins as well.

**Comment by Dris101** [comment]
I have the same issue. I have just moved some projects over to a new machine on which I did a clean install of sbt 0.13.11. Using Scala 2.11.8 and referencing `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")` from `~\.sbt\0.13\plugins.sbt`  I get the following:-

warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[info] Resolving org.scala-lang#scala-library;2.11.8 ...
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13)

Any suggestion on how to fix this would be much appreciated. These projects were compiling fine on my old machine. All my local ivy caches are empty on my new machine as it is a new build. I am not sure if that is why I didn't get this issue before.

**Comment by beezerbt** [comment]
I am simply trying to use _sbt eclipse_ to configure a project with the above settings (i.e. same versions mentioned by Dris101) and I get the same error. Is there a fallback?

**Comment by Dris101** [comment]
I have fixed the issue for my project by deleting `~\.sbt\0.13\plugins.sbt` entirely and putting the `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")` in `project\plugins.sbt`. I think the plugins should be looking to resolve vs. the scala version that sbt was built with (which I think is 2.10), not the scala version that the project is using (2.11 in my case). In any case, using `project\plugins.sbt` worked for me. The artifact at `https://bintray.com/sbt/sbt-plugin-releases/sbteclipse/4.0.0/view#files/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.10/sbt_0.13/4.0.0` does exist but not one called `.../scala_2.11/...`

**Comment by aaronwitt27** [comment]
Has anyone been able to resolve this issue?  I'm trying to set up my machine so that sbteclipse is a global plugin, and not part of each project's source.

At SBT_HOME, I have build.sbt and plugins/plugins.sbt.

Here's `SBT_HOME\build.sbt`:

```
resolvers += Classpaths.typesafeResolver

// Download Source and Javadocs with binaries
EclipseKeys.withSource := true
EclipseKeys.withJavadoc := true

// Compile the project before generating Eclipse files, so that generated .scala or .class files for views and routes are present
EclipseKeys.preTasks := Seq(compile in Compile)

// Java project. Don't expect Scala IDE
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           

// Use .class files instead of generated .scala files for views and routes
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)
```

And here's `SBT_HOME\plugins\plugins.sbt`:

```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")
```

My projects use `scalaVersion := "2.11.8"`, as specified in their respective build.sbt files.  Since I'm currently upgrading from 2.3.x, my projects are using `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.6")`, as specified in their respective project/plugins.sbt files.  And lastly, each project specifies `sbt.version=0.13.11`, in project/build.properties.

As stated by others, I'd like to configure sbteclipse globally, to be used in any project for generating Eclipse project files.  Am I missing configuration?  Am I misconfiguring?

**Comment by 2m** [comment]
@aaronwitt27 your setup looks correct. What error are you getting?

@Dris101 I noticed that you put `addSbtPlugin(...)` to `~\.sbt\0.13\plugins.sbt`. This is incorrect. It should be under `~/.sbt/0.13/plugins/` directory. Anyway, I tried to reproduce the same situation in a docker container (I used [this image](https://hub.docker.com/r/williamyeh/sbt/)), because I do not have a clean system, but I was unable to reproduce the issue. When following your setup I do not get `eclipse` command added to the project as expected and no error shows up.

**Comment by beezerbt** [comment]
Thanks to @Dris101 it builds now.
The documentation on the sbt site is flawed. 
The HelloWorld example should be a packaging one...who cares about running it from sbt .... 

So, in short:
1. Remove the plugins file from your home/.sbt/
2. Add the plugins in your baseDir/project/plugins.sbt file (i.e. the sbteclipse dependency with version 4.0.0)
3. Have your simple build.sbt have your version of scala

Of course running the jar file shows me that the are libs missing !!!! 
So, once again, the documentation on sbt for newbies is FALWED.

**Comment by beezerbt** [comment]
In fact, once you try to build with sbt you will see how woeful the documentation actually is, cause you will very quickly understand the need for the assembly plugin.
I am going to look at gradle...this sbt is ..... well.... you make up your own mind.

**Comment by bjornregnell** [comment]
I also suddenly got
[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
in projects that used to work. Is the plugin broken or removed?

**Comment by bjornregnell** [comment]
I found a work-around: do not use any global version settings in ~.sbt/0.13/global.sbt -- neither scalaVersion nor sbtVersion -- as these will confuse the resolution process. 
Hence, the scala 2.10 and 2.11 mismatch can be caused by adding scalaVersion to your global.sbt... (And it not just the plugins-file in .sbt, from comment above, that can cause confusion...)
Then also make sure that all build.properties in all sub-projects are aligned with your main project. When new versions of sbt things may break so it is wise to nail it to e.g. sbt.version := 0.13.12 in build.properties and also include that in all sub-projects or else another sbt version might kick in. 

This issue is likely to bite more people, so I think the sbtplugin should be made available for 2.11, and also perhaps the sbt documentation on global settings could be improved. (I don't really see the point of global default settings if the can't be overridden by a project's specific settings...)

Here is a minimal test case that reproduced the problem on my machines (linux ubuntu 14.04, also tested correspondingly on win7):
```
$ cat >~/.sbt/0.13/global.sbt
scalaVersion := "2.11.8"

sbtVersion := "0.13.12"

$ mkdir test-sbteclipse
$ cd test-sbteclipse
$ mkdir project
$ echo 'addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")' > project/plugins.sbt
$ sbt
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13)
[warn] 
```

**Comment by KrakenChaos** [comment]
I am having the same issue and tried to follow solutions provided by @Dris101 and @beezerbt but it does not work for me.

**Comment by bjornregnell** [comment]
Have you tried removing ~/.sbt/0.13/global.sbt ?

**Comment by KrakenChaos** [comment]
Yeah, I got it working by removing 
`addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")`
from project_folder/project/plugins.sbt
and putting in  ~/.sbt/0.13/plugins/plugins.sbt file.

**Comment by joney000** [comment]
remove ~/.sbt/boot/sbt.boot.lock and again try . It worked for me.

**Comment by devndone** [comment]
while running sbt without any project setup on command line does give same issue.. 
I got it working by removing
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")
from ~/.sbt/0.13/plugins/plugins.sbt 
(Later when I need to create a project n run I'll add it to project_folder/project/plugins.sbt, I think it should work)

**Comment by joney000** [comment]
Thanks !!

**Comment by rnevitt** [comment]
I see this issue was resolved for you, but just in case it happens to somebody else I'd like to point out that the "project/plugins.sbt" is actually a folder named project inside your project's folder.   This cost me about 10 minutes of confusion, because I'd put the plugins.sbt in my project's folder.

**Comment by bpossolo** [comment]
holy shit @rnevitt thank you! what a time sink

**Comment by sachinjha1** [comment]
Newer version of plugin worked for me:

```addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")```

**Comment by mkumar18** [comment]
For me following settings in the plugin.sbt worked.

addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.8")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")

**Comment by o-pikozh** [comment]
I've found a workaround.

First, let me describe my specific case to make you sure whether you have the same problem or not. Then I'll describe a successful workaround. At the end I'll describe my less successful tries to get more elegant solutions.

### My specific issue

I'm using KUbuntu Bionic (18.04.1 LTS). I'm using the latest available stable versions of the software: sbt is 1.2.6, `scalaVersion` is by default 2.12.7 and sbteclipse-plugin I'm trying to get is 5.2.4. I'm trying to get it by adding the following line to `$MY_PROJECT_DIR/plugins.sbt`:

     addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")

What I get from `sbt compile` is the following (excerpt):

    [info] Updating ...
    [warn]  module not found: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4
    [warn] ==== local: tried
    [warn]   /home/$MY_USER_NAME/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml
    [warn] ==== public: tried
    [warn]   https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.2.4/sbteclipse-plugin-5.2.4.pom
    [warn] ==== local-preloaded-ivy: tried
    [warn]   /home/$MY_USER_NAME/.sbt/preloaded/com.typesafe.sbteclipse/sbteclipse-plugin/5.2.4/ivys/ivy.xml
    [warn] ==== local-preloaded: tried
    [warn]   file:////home/$MY_USER_NAME/.sbt/preloaded/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.2.4/sbteclipse-plugin-5.2.4.pom
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  ::          UNRESOLVED DEPENDENCIES         ::
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 
    [warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
    [warn]          com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=1.0)
    [warn] 
    [warn]  Note: Unresolved dependencies path:
    [warn]          com.typesafe.sbteclipse:sbteclipse-plugin:5.2.4 (scalaVersion=2.12, sbtVersion=1.0) (/home/$MY_USER_NAME/Documents/Tries/Test1/build.sbt#L10-11)
    [warn]            +- default:test1_2.12:0.1.0-SNAPSHOT
    [error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found
    [error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
    [error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
    [error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
    [error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
    [error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
    [error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
    [error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
    [error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
    [error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
    [error]         at xsbt.boot.Using$.withResource(Using.scala:10)
    [error]         at xsbt.boot.Using$.apply(Using.scala:9)
    [error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
    [error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
    [error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
    [error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
    [error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
    [error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
    [error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
    [error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
    [error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
    [error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
    [error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
    [error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
    [error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
    [error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
    [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
    [error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
    [error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
    [error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2556)
    [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
    [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
    [error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
    [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
    [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
    [error]         at sbt.Execute.work(Execute.scala:278)
    [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
    [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
    [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
    [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    [error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
    [error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    [error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
    [error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    [error]         at java.base/java.lang.Thread.run(Thread.java:844)
    [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.2.4: not found

### Workaround

In the sbt's output I see the following lines:

    [warn] ==== local: tried
    [warn]   /home/$MY_USER_NAME/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml

That means that sbt first tries to get sbteclipse's first locally. From [the 2m's comment](https://github.com/sbt/sbteclipse/issues/315#issuecomment-214714282) we know the correct remote location of the corresponding files ([`ivy.xml`](https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml) and [`sbteclipse-plugin.jar`](https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/jars/sbteclipse-plugin.jar)). So we can download these files manually and put them to the corresponding local folders:

    mkdir -p ~/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys
    cd ~/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys
    wget https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml
    mkdir -p ~/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/jars
    cd ~/.ivy2/local/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/jars
    wget https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/jars/sbteclipse-plugin.jar

### Unsuccessful search for cleaner solutions

Adding the following resolvers didn't help:

  * `resolvers += Resolver.bintrayRepo("sbt", "sbt-plugin-releases")`

    URLs don't match:

        https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/5.2.4/ivys/ivy.xml #correct
        https://dl.bintray.com/sbt/sbt-plugin-releases/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/5.2.4/sbteclipse-plugin-5.2.4.pom #tried with Resolver.bintrayRepo("sbt", "sbt-plugin-releases")

  * `resolvers += Resolver.jcenterRepo`

    http://jcenter.bintray.com seems to omit sbt-eclipse at all.

  * `resolvers += sbtResolver.value` (which I believe to be the same as `resolvers += Resolver.typesafeIvyRepo("releases")`)

    The typesafe-ivy-releases repository contains [only old releases of the sbt-eclipse plugin](https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/).

**Comment by o-pikozh** [comment]
Hmm, sorry, it seems that I just put the line `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")` into a wrong place. Putting it into `$MY_PROJECT_DIR/project/site.sbt` and/or `~/.sbt/plugins/1.0/build.sbt` works fine. Sorry for disturbing.

**Comment by Helsonkumar** [comment]
I got this resolved as follows:
1. Clean all files generated by previous erroneous runs. (This also includes removing plugins.sbt from project root directory)
2. Create a new file plugins.sbt under "/project_root_dir/project/" folder
3. Insert -> addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4") to plugins.sbt file
4. Run "sbt package" from project root directory followed by "sbt eclipse" command
5. Once succeeded, go to eclipse and import your sbt built project as "Import Existing Project"
