### ISSUE TITLE
global sbteclipse cannot be resolved

### ISSUE THREAD

**Issue by aaronwitt27** [typesafehub/sbteclipse#318]
I'm upgrading from Activator 2.3.x to 2.4.x (and eventually, to 2.5.x).  As part of this migration, I can no longer use the `activator eclipse` command to generate an Eclipse project from the Play application.

I work on a team, some of which use IntelliJ.  So, I cannot make these changes for each project, since it'd be unuseful for the IntelliJ users, and it'd be inappropriate to version with the project source.

I've been following [these](https://github.com/typesafehub/sbteclipse) instructions.  Here are the steps for migration that I've taken so far:
1. Change project\plugins.sbt to use 2.4.6  
2. In project\application.conf, change `evolutionplugin=disabled` to `play.evolutions.enabled=false`  
3. In project\build.sbt, remove `javaEbean` from `libraryDependencies`  
4. **Eclipse Users (relevant to this post)**  
   a. Download and install SBT: http://www.scala-sbt.org/  
   b. Create SBT_HOME environment variable  
   c. Add `%SBT_HOME%\bin` to `PATH`  
   d. Create 'plugins' folder at `%SBT_HOME%`  
   e. Create plugins.sbt file in plugins directory  
   f. Add the following line to global plugins.sbt:  
       `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")`  
   g. Edit `%SBT_HOME%\conf\sbtopts` to specify SBT installation directory:  
       `-sbt-dir   C:/dev/sbt/plugins`  
   h. Create build.sbt file at `%SBT_HOME%\plugins`  
   i. Add the following SBT Eclipse Setting Keys to aforementioned build.sbt:  

```
resolvers ++= Seq(
    "Ivy Releases" at "https://repo.typesafe.com/typesafe/ivy-releases/",
    "Maven Releases" at "https://repo.typesafe.com/typesafe/maven-releases/"
)

// Download Source and Javadocs with binaries
EclipseKeys.withSource := true
EclipseKeys.withJavadoc := true

// Compile the project before generating Eclipse files, so that generated .scala or .class files for views and routes are present
EclipseKeys.preTasks := Seq(compile in Compile)

// Java project. Don't expect Scala IDE
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           

// Use .class files instead of generated .scala files for views and routes
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)
```

At this point, I should be able to create an Eclipse project, but it cannot resolve sbteclipse:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (scalaVersion=2.11, sbtVersion=0.13) (C:\dev\sbt\plugins\plugins.sbt#L1-2)
[warn]            +- gateway-api:gateway-api_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
[error] Could not create Eclipse project files:
[error] Error evaluating task 'scalacOptions': error
[error] Error evaluating task 'externalDependencyClasspath': error
```

So, you can see from the steps outlined above, I'm trying to allow for us Eclipse users to create projects from the Play services.  I downloaded SBT, extracted it to my dev folder, and started making global changes there.  

I have SBT installed to `C:\dev\sbt`.  At `SBT_HOME`, I also have a folder, `plugins`, which in turn contains `plugins.sbt` and `build.sbt`.

Contents of `C:\dev\sbt\plugins\build.sbt`:

```
resolvers ++= Seq(
    "Ivy Releases" at "https://repo.typesafe.com/typesafe/ivy-releases/",
    "Maven Releases" at "https://repo.typesafe.com/typesafe/maven-releases/"
)

// Download Source and Javadocs with binaries
EclipseKeys.withSource := true
EclipseKeys.withJavadoc := true

// Compile the project before generating Eclipse files, so that generated .scala or .class files for views and routes are present
EclipseKeys.preTasks := Seq(compile in Compile)

// Java project. Don't expect Scala IDE
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java           

// Use .class files instead of generated .scala files for views and routes
EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)
```

Contents of `C:\dev\sbt\plugins\plugins.sbt`:

```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")
```

Project exists at `C:\dev\eclipse\workspaces\company\project`.  In Cygwin, I navigate to that location and execute `sbt eclipse`, which according to my understanding should work.  But, like I said, I get an error, and it doesn't work.

Can someone help me get this set up correctly so that I can create Eclipse project files for a Play service, and continue on my happy lil migration journey?

**Comment by BorisHollas** [comment]
Same problem here:
`[error] (*:update) sbt.internal.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;4.0.0: not found
`

**Comment by ryanstull** [comment]
I'm getting this same problem as well

**Comment by bjornregnell** [comment]
I'm suddenly getting this problem as well for projects that worked fine yesterday. 
Is there some way to download and keep a working version of the plug-in locally, to get around this show stopper?

**Comment by amarkanday** [comment]
Same issue 

sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;5.1.0: not found

my directory structure
.
./build.sbt
./project
./project/plugins.sbt

No dependency in the build file, keeping is real simple for debugging 

```
cat build.sbt 
name := "Read Friend Network JanusGraph"
version := "1.0"

```

```
cat project/plugins.sbt 
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.1.0")

```

Everything worked fine before

**Comment by mkurz** [comment]
Please use latest version 5.2.2:
```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.2")
```

**Comment by howardlinus** [comment]
this should be updated in your wiki. I spent an hour trying to figure out why 4.0.0 doesn't work for me until find out about this answer -- "5.2.2".

**Comment by benmccann** [comment]
Thanks for pointing that out. I've deleted that page from the wiki and pointed to the README instead
