### ISSUE TITLE
java.lang.ClassNotFoundException: scala.Int

### ISSUE THREAD

**Issue by dmassart** [typesafehub/sbteclipse#348]
On Mac Os X, when upgrading an Akka project from sbt 0.13.15 to sbt 1.0.1 I get a java.lang.ClassNotFoundException: scala.Int when starting the actor system (things go smoothly when upgrading non-Akka projects).

[error] java.lang.ClassNotFoundException: scala.Int
[error] 	at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:74)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:21)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:20)
[error] 	at akka.serialization.Serialization.$anonfun$bindings$3(Serialization.scala:311)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
[error] 	at akka.serialization.Serialization.<init>(Serialization.scala:309)
[error] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:15)
[error] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:12)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:880)
[error] 	at akka.actor.ExtensionId.apply(Extension.scala:77)
[error] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
[error] 	at akka.serialization.SerializationExtension$.apply(SerializationExtension.scala:12)
[error] 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:203)
[error] 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:796)
[error] 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:793)
[error] 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:793)
[error] 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:809)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:244)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:287)
[error] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:232)
[error] 	at ActorDemo$.main(actor.scala:70)
[error] 	at ActorDemo.main(actor.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:120)
[error] 	at sbt.Run.run(Run.scala:73)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1155)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1150)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:331)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:254)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 20 s, completed Sep 5, 2017 6:52:27 PM

**Comment by benmccann** [comment]
What version of sbteclipse are you using? Can you please be sure to test with 5.2.2?

**Comment by jonas-db** [comment]
I have the same problem with 1.0.3. Downgrading to 0.13.16 made it work (using scala 2.12.4)
